export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ADMIN_LOADED = "ADMIN_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const LOGOUT = "LOGOUT";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const GET_PROFILE = "GET_PROFILE";
export const GET_BUYER_PROFILES = "GET_BUYER_PROFILES";
export const GET_SELLER_PROFILES = "GET_SELLER_PROFILES";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";

export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
